In [2]:
import pandas as pd

In [3]:
dataset=pd.read_csv("insurance_pre.csv")

In [4]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [5]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [7]:
dataset.astype(int)

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age','children','sex_male','smoker_yes']]

In [10]:
independent

      age  children  sex_male  smoker_yes
0      19         0     False        True
1      18         1      True       False
2      28         3      True       False
3      33         0      True       False
4      32         0      True       False
...   ...       ...       ...         ...
1333   50         3      True       False
1334   18         0     False       False
1335   18         0     False       False
1336   21         0     False       False
1337   61         0     False        True

[1338 rows x 4 columns]

In [11]:
dependent=dataset[['charges']]

In [12]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [14]:
x_train

      age  children  sex_male  smoker_yes
1163   18         0     False       False
196    39         0     False       False
438    52         5     False       False
183    44         0     False       False
1298   33         2      True       False
...   ...       ...       ...         ...
763    27         0      True       False
835    42         2      True       False
1216   40         0      True       False
559    19         0      True       False
684    33         1     False       False

[936 rows x 4 columns]

In [15]:
#Standardization
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [118]:
#https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html
from sklearn.svm import SVR
regressor=SVR(kernel="sigmoid",C=1000)
regressor.fit(x_train,y_train)

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1000, kernel='sigmoid')

In [119]:
regressor.intercept_

array([12092.41525102])

In [120]:
regressor.n_support_

array([936], dtype=int32)

In [121]:
y_pred=regressor.predict(x_test)

In [122]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [123]:
r_score

-0.20352906403942272