In [34]:
import pandas as pd

In [35]:
dataset=pd.read_csv('insurance_pre.csv')

In [36]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [37]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [38]:
dataset=dataset.astype(int)

In [39]:
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [40]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [41]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [52]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [53]:
#Split into training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [54]:
#from sklearn.preprocessing import StandardScaler
#sc=StandardScaler()
#x_train=sc.fit_transform(x_train)
#x_test=sc.transform(x_test)

In [55]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
#param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[10,100,1000,2000,3000],'gamma':['auto','scale']}
param_grid={'kernel':['rbf','poly','sigmoid','linear'],'C':[3000],'gamma':['auto','scale']}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)

#fitting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [3000], 'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [56]:
#print best parameter after tuning
#print(grid.best_params)
re=grid.cv_results_
print("The R_Score value for the best parameter {}:".format(grid.best_params_))

The R_Score value for the best parameter {'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}:

In [57]:
table=pd.DataFrame.from_dict(re)

In [58]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.288214,0.015283,0.058867,0.001780,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.034186,0.112550,-0.118686,-0.064411,-0.080721,-0.023417,0.084671,3
1,1756.166019,347.069493,0.009374,0.001604,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",-272.860395,-125.914474,-64.681694,-91.644387,-99.152340,-130.850658,73.636103,8
2,0.092170,0.000775,0.023331,0.001363,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.054234,-0.023634,-0.160075,-0.123096,-0.141320,-0.100472,0.052488,5
3,3.198106,2.420318,0.018145,0.002345,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.637189,0.656938,0.584862,0.646117,0.554280,0.615877,0.039524,1
4,0.137558,0.001187,0.055928,0.001202,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",-0.134717,0.036359,-0.240514,-0.203312,-0.157514,-0.139940,0.095445,6
5,0.192294,0.016673,0.022002,0.002382,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",-0.045914,0.148874,-0.128435,-0.097284,-0.064028,-0.037357,0.097317,4
6,0.140642,0.045059,0.050559,0.044446,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-9.205920,-10.183802,-6.970701,-9.374830,-7.280109,-8.603073,1.254799,7
7,2.872615,1.828818,0.019875,0.000421,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.637189,0.656938,0.584862,0.646117,0.554280,0.615877,0.039524,1

In [50]:


age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 30
BMI: 40
Children: 2
Sex Male 0 or 1: 1
Smoker Yes 0 or 1: 1

In [51]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[3383007.70163853]