In [33]:
import pandas as pd

In [34]:
dataset=pd.read_csv('insurance_pre.csv')

In [35]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [36]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [37]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [38]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [39]:
independent=dataset[['age','bmi','children','sex_male','smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [40]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [41]:
#Split into training set and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [42]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [43]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
para_grid={'criterion':['squared_error','absolute_error','poisson'],'splitter':['best','random']}
grid=GridSearchCV(DecisionTreeRegressor(),para_grid,refit=True,verbose=3,n_jobs=-1)
#fitting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [44]:
re=grid.cv_results_
print("The R_Score value for the best parameter{}:".format(grid.best_params_))

The R_Score value for the best parameter{'criterion': 'absolute_error', 'splitter': 'random'}:

In [45]:
table=pd.DataFrame.from_dict(re)

In [46]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.019092,0.004018,0.008175,0.002135,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.737300,0.515304,0.746057,0.569666,0.672649,0.648195,0.091588,2
1,0.012304,0.004530,0.006988,0.003308,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.676949,0.612708,0.714338,0.497951,0.633976,0.627184,0.073524,5
2,0.064754,0.003315,0.008104,0.000820,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.667257,0.628051,0.692834,0.555127,0.617340,0.632122,0.047082,4
3,0.055938,0.004094,0.008476,0.001386,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.643770,0.638096,0.684235,0.662801,0.668961,0.659573,0.016839,1
4,0.020154,0.002034,0.007967,0.001550,poisson,best,"{'criterion': 'poisson', 'splitter': 'best'}",0.743669,0.491460,0.751937,0.566005,0.669350,0.644484,0.101565,3
5,0.014982,0.003511,0.006586,0.001893,poisson,random,"{'criterion': 'poisson', 'splitter': 'random'}",0.716997,0.545998,0.617010,0.566169,0.594096,0.608054,0.059580,6

In [47]:
age_input=float(input("Age"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age 32
BMI: 43
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [48]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[36580.]