In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'n_estimators':[10,100,1000],'criterion':['squared_error','absolute_error','poisson'],'max_features':['sqrt','log2']}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
#fitting the model for grid search
grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100, 1000]},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_Score value for the best parameer{}:".format(grid.best_params_))

The R_Score value for the best parameer{'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 1000}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.068207,0.018348,0.010429,0.001950,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844316,0.776791,0.776768,0.790283,0.746729,0.786977,0.032021,16
1,0.397820,0.049376,0.019738,0.001025,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.865381,0.784612,0.801177,0.823949,0.764585,0.807941,0.034714,11
2,3.311518,0.036180,0.152153,0.005790,squared_error,sqrt,1000,"{'criterion': 'squared_error', 'max_features':...",0.866114,0.787929,0.798927,0.823822,0.766199,0.808598,0.034230,8
3,0.042909,0.003848,0.006150,0.000569,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.844204,0.787140,0.787576,0.807527,0.743752,0.794040,0.032609,14
4,0.328773,0.003518,0.019476,0.001607,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.864430,0.789271,0.800533,0.824381,0.763462,0.808415,0.034182,9
5,3.217197,0.016184,0.136880,0.004372,squared_error,log2,1000,"{'criterion': 'squared_error', 'max_features':...",0.864147,0.790080,0.800792,0.823506,0.765794,0.808864,0.033298,7
6,0.088193,0.003120,0.005265,0.000163,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.842384,0.768375,0.768431,0.784570,0.762941,0.785340,0.029428,18
7,0.804195,0.009470,0.018490,0.001608,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.865084,0.785117,0.800726,0.829642,0.773455,0.810805,0.033038,4
8,7.944118,0.029095,0.137406,0.005622,absolute_error,sqrt,1000,"{'criterion': 'absolute_error', 'max_features'...",0.862383,0.796951,0.807597,0.824394,0.770026,0.812270,0.030657,3
9,0.083986,0.001817,0.004949,0.000241,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.848712,0.773843,0.794553,0.794345,0.766696,0.795630,0.028748,13
10,0.792925,0.007117,0.016296,0.000637,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.861820,0.798471,0.807018,0.823213,0.771525,0.812409,0.029843,2
11,7.897706,0.068796,0.130474,0.005692,absolute_error,log2,1000,"{'criterion': 'absolute_error', 'max_features'...",0.865171,0.796722,0.807903,0.829148,0.767538,0.813296,0.032680,1
12,0.038991,0.000539,0.005363,0.000582,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.841823,0.770918,0.781416,0.819604,0.749284,0.792609,0.033537,15
13,0.340839,0.001778,0.017832,0.000983,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859962,0.791024,0.800341,0.825409,0.763110,0.807969,0.032757,10
14,3.400430,0.027756,0.140395,0.003263,poisson,sqrt,1000,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.862951,0.788898,0.802529,0.824710,0.766943,0.809206,0.032778,6
15,0.040499,0.000991,0.005070,0.000267,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.844386,0.767044,0.778103,0.786537,0.757533,0.786721,0.030459,17
16,0.347584,0.003355,0.017903,0.000986,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.861808,0.793386,0.798057,0.824489,0.759984,0.807545,0.034012,12
17,3.168975,0.276369,0.107816,0.013150,poisson,log2,1000,"{'criterion': 'poisson', 'max_features': 'log2...",0.863526,0.789454,0.801594,0.823994,0.767953,0.809304,0.032616,5

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 44
BMI: 66
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[45826.037]

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(