In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
dataset=dataset.astype(int)
dataset

      age  bmi  children  charges  sex_male  smoker_yes
0      19   27         0    16884         0           1
1      18   33         1     1725         1           0
2      28   33         3     4449         1           0
3      33   22         0    21984         1           0
4      32   28         0     3866         1           0
...   ...  ...       ...      ...       ...         ...
1333   50   30         3    10600         1           0
1334   18   31         0     2205         0           0
1335   18   36         0     1629         0           0
1336   21   25         0     2007         0           0
1337   61   29         0    29141         0           1

[1338 rows x 6 columns]

In [8]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [9]:
independent=dataset[['age','bmi','children','sex_male','smoker_yes']]
independent

      age  bmi  children  sex_male  smoker_yes
0      19   27         0         0           1
1      18   33         1         1           0
2      28   33         3         1           0
3      33   22         0         1           0
4      32   28         0         1           0
...   ...  ...       ...       ...         ...
1333   50   30         3         1           0
1334   18   31         0         0           0
1335   18   36         0         0           0
1336   21   25         0         0           0
1337   61   29         0         0           1

[1338 rows x 5 columns]

In [10]:
dependent=dataset[['charges']]
dependent

      charges
0       16884
1        1725
2        4449
3       21984
4        3866
...       ...
1333    10600
1334     2205
1335     1629
1336     2007
1337    29141

[1338 rows x 1 columns]

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
param_grid={'n_estimators':[10,100,1000],'criterion':['squared_error','absolute_error','poisson'],'max_features':['sqrt','log2']}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [10, 100, 1000]},
             verbose=3)

In [13]:
re=grid.cv_results_
print("The R_Scorevalue for the best parameter{}:".format(grid.best_params_))

The R_Scorevalue for the best parameter{'criterion': 'absolute_error', 'max_features': 'log2', 'n_estimators': 100}:

In [14]:
table=pd.DataFrame.from_dict(re)

In [15]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.124156,0.017586,0.017804,0.003266,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.844403,0.777810,0.835993,0.817413,0.823454,0.819815,0.023021,13
1,0.965433,0.029909,0.049237,0.002447,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.855969,0.773079,0.847193,0.822115,0.839144,0.827500,0.029409,10
2,8.953881,0.094957,0.398319,0.008472,squared_error,sqrt,1000,"{'criterion': 'squared_error', 'max_features':...",0.855445,0.775400,0.853771,0.823120,0.838570,0.829261,0.029366,8
3,0.104742,0.003202,0.013576,0.001776,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.834181,0.754486,0.828091,0.792305,0.804564,0.802725,0.028537,18
4,0.890861,0.004915,0.046839,0.003470,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.855756,0.774997,0.853818,0.822974,0.838160,0.829141,0.029558,9
5,8.867685,0.134548,0.369799,0.010587,squared_error,log2,1000,"{'criterion': 'squared_error', 'max_features':...",0.855211,0.774523,0.856169,0.824830,0.838661,0.829879,0.029999,7
6,0.282512,0.005376,0.012981,0.000977,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.847045,0.733332,0.830803,0.816013,0.826241,0.810687,0.039952,15
7,2.730154,0.042491,0.045329,0.001682,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856789,0.773790,0.857844,0.828605,0.839599,0.831325,0.030783,4
8,27.020086,0.254158,0.366063,0.015460,absolute_error,sqrt,1000,"{'criterion': 'absolute_error', 'max_features'...",0.857580,0.775905,0.854581,0.828929,0.842117,0.831823,0.029741,3
9,0.278426,0.010801,0.012129,0.001082,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.816961,0.760184,0.832713,0.806276,0.814437,0.806114,0.024511,17
10,2.706303,0.047946,0.044695,0.002099,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.856450,0.773699,0.861315,0.828373,0.844199,0.832807,0.031670,1
11,26.795493,0.408248,0.358209,0.068994,absolute_error,log2,1000,"{'criterion': 'absolute_error', 'max_features'...",0.858907,0.775847,0.856006,0.827838,0.842278,0.832175,0.030253,2
12,0.107450,0.003335,0.012425,0.000462,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.831084,0.751622,0.825998,0.809493,0.829512,0.809542,0.029961,16
13,0.941700,0.012656,0.044112,0.001979,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.850780,0.774211,0.849436,0.822968,0.836345,0.826748,0.028138,11
14,9.481155,0.037740,0.385996,0.014704,poisson,sqrt,1000,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.856651,0.776058,0.856098,0.823939,0.838905,0.830330,0.029721,6
15,0.106929,0.002886,0.012734,0.000772,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.836558,0.762508,0.843358,0.810231,0.820911,0.814713,0.028571,14
16,0.958986,0.009343,0.046508,0.001343,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.853770,0.772791,0.852163,0.820907,0.833392,0.826605,0.029549,12
17,9.128184,0.278846,0.346616,0.011432,poisson,log2,1000,"{'criterion': 'poisson', 'max_features': 'log2...",0.856573,0.775899,0.856405,0.824304,0.840160,0.830668,0.029879,5

In [16]:
age_input=float(input("Age"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age 44
BMI: 66
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[45325.925]

C:\Users\dell\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(